BEGIN;

DROP FUNCTION IF EXISTS publish_config_snapshot(text,bigint,integer,jsonb,text,text,text,text,text,text,text);
DROP FUNCTION IF EXISTS update_tenant_configuration(text,bigint,text,bigint,integer,bigint,bigint,character,integer,text,text,numeric,text,text,bigint,text,text,text,text,text);
DROP FUNCTION IF EXISTS transition_tenant_status(text,bigint,text,text,text,text,text,text,text,text);
DROP FUNCTION IF EXISTS transition_agent_app_status(text,text,bigint,text,text,text,text,text,text);
DROP FUNCTION IF EXISTS rollback_agent_app_revision(text,text,bigint,bigint,text,text,text,text,text);
DROP FUNCTION IF EXISTS publish_agent_app_revision(text,text,bigint,bigint,bigint,text,text,text,text,text,text);
DROP TRIGGER IF EXISTS config_snapshot_immutable ON config_snapshot;
DROP FUNCTION IF EXISTS reject_published_config_change();
DROP TRIGGER IF EXISTS agent_app_revision_published_immutable ON agent_app_revision;
DROP FUNCTION IF EXISTS reject_published_revision_change();
DROP TRIGGER IF EXISTS agent_app_revision_knowledge_draft_only ON agent_app_revision_knowledge;
DROP TRIGGER IF EXISTS agent_app_revision_tool_draft_only ON agent_app_revision_tool;
DROP FUNCTION IF EXISTS guard_revision_child_write();
DROP TRIGGER IF EXISTS agent_app_current_revision_published ON agent_app;
DROP FUNCTION IF EXISTS guard_agent_app_current_revision();
DROP TRIGGER IF EXISTS agent_app_identity_version_guard ON agent_app;
DROP FUNCTION IF EXISTS reject_agent_app_identity_change();
DROP TRIGGER IF EXISTS tenant_maintain_update_trg ON tenant;
DROP FUNCTION IF EXISTS maintain_tenant_update();
ALTER TABLE tenant DROP CONSTRAINT IF EXISTS tenant_active_config_fk;
ALTER TABLE tenant DROP CONSTRAINT IF EXISTS tenant_default_backend_profile_fk;
ALTER TABLE tenant DROP CONSTRAINT IF EXISTS tenant_default_agent_app_fk;
DROP TABLE IF EXISTS backend_binding;
DROP TABLE IF EXISTS backend_profile;
DROP TABLE IF EXISTS channel_binding;
DROP TABLE IF EXISTS config_snapshot;
ALTER TABLE agent_app DROP CONSTRAINT IF EXISTS agent_app_current_revision_fk;
DROP TABLE IF EXISTS agent_app_revision_knowledge;
DROP TABLE IF EXISTS agent_app_revision_tool;
DROP TABLE IF EXISTS agent_app_change;
DROP TABLE IF EXISTS agent_app_revision;
DROP TABLE IF EXISTS agent_app;
DROP TABLE IF EXISTS tenant_status_change;
DROP TABLE IF EXISTS tenant;
DROP TABLE IF EXISTS outbox;

COMMIT;
