BEGIN;
DROP FUNCTION IF EXISTS public.expire_confirmations(timestamptz,integer);
DROP FUNCTION IF EXISTS public.decide_confirmation(text,text,text,boolean,bigint,timestamptz);
DROP FUNCTION IF EXISTS public.suspend_turn(text,text,text,text,text,text,bigint,bigint,bigint,jsonb,jsonb,text,text,text,text,bigint,text,text,bigint,text,bigint,bigint,bigint,timestamptz,jsonb);
DROP TABLE IF EXISTS public.interaction_payload;
DROP TABLE IF EXISTS public.tool_result_payload;
DROP TABLE IF EXISTS public.tool_attempt;
DROP TABLE IF EXISTS public.confirmation_grant;
DROP TABLE IF EXISTS public.confirmation;
COMMIT;
