package webui

const webUIHTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>tRPC Agent WebUI IM</title><link rel="stylesheet" href="/webui/style.css"></head>
<body><main><header><div><span class="eyebrow">LOCAL CHANNEL ADAPTER</span><h1>WebUI IM</h1></div><div id="status" class="status">未连接</div></header>
<section class="settings"><label>Route Key<input id="route" autocomplete="off"></label><label>Account ID<input id="account" autocomplete="off"></label>
<label>User ID<input id="user" value="local-user" autocomplete="off"></label><label>Chat ID<input id="chat" value="local-chat" autocomplete="off"></label>
<label class="wide">Channel Token<input id="token" type="password" autocomplete="off"></label><button id="connect" type="button">连接</button></section>
<section id="timeline" class="timeline" aria-live="polite"><div class="empty">连接后发送消息，回复会经过完整 durable Channel 链路返回这里。</div></section>
<form id="composer"><textarea id="text" rows="2" maxlength="32768" placeholder="输入消息…" required></textarea><button type="submit">发送</button></form>
</main><script src="/webui/app.js" defer></script></body></html>`

const webUICSS = `:root{color-scheme:dark;--bg:#0c1017;--panel:#141b25;--line:#273244;--ink:#eef4ff;--muted:#8fa0b8;--accent:#79e0c3;--accent2:#90b4ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#17283b 0,transparent 38%),var(--bg);color:var(--ink);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,sans-serif}main{width:min(960px,calc(100% - 28px));margin:28px auto;display:grid;gap:16px}header,.settings,.timeline,form{border:1px solid var(--line);background:color-mix(in srgb,var(--panel) 92%,transparent);border-radius:18px;box-shadow:0 18px 55px #0005}header{display:flex;justify-content:space-between;align-items:center;padding:22px 26px}h1{font-size:34px;line-height:1;margin:7px 0 0;letter-spacing:-.04em}.eyebrow{font:700 11px/1 ui-monospace,monospace;color:var(--accent);letter-spacing:.15em}.status{padding:7px 11px;border:1px solid var(--line);border-radius:999px;color:var(--muted)}.status.ok{border-color:#347865;color:var(--accent)}.settings{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:18px}.settings label{display:grid;gap:6px;color:var(--muted);font-size:12px}.settings .wide{grid-column:1/-1}input,textarea{width:100%;border:1px solid var(--line);border-radius:11px;background:#0b111a;color:var(--ink);padding:11px 12px;font:inherit;outline:none}input:focus,textarea:focus{border-color:var(--accent2)}button{border:0;border-radius:11px;background:var(--accent);color:#06251d;padding:11px 18px;font-weight:800;cursor:pointer}.settings button{grid-column:1/-1}.timeline{min-height:390px;max-height:58vh;overflow:auto;padding:20px;display:flex;flex-direction:column;gap:12px}.empty{margin:auto;color:var(--muted);text-align:center}.bubble{max-width:78%;padding:11px 14px;border-radius:15px;background:#202b3a;white-space:pre-wrap;overflow-wrap:anywhere}.bubble.me{align-self:flex-end;background:#254b48}.bubble .meta{display:block;margin-top:6px;color:var(--muted);font:10px/1.3 ui-monospace,monospace}form{display:grid;grid-template-columns:1fr auto;gap:12px;padding:14px}textarea{resize:vertical;min-height:52px}@media(max-width:640px){main{margin:14px auto}.settings{grid-template-columns:1fr}.settings .wide{grid-column:auto}.bubble{max-width:92%}header{padding:18px}h1{font-size:28px}}`

const webUIJS = `const $=id=>document.getElementById(id);let connected=false,timer=null,seen=new Set();
const enc=new TextEncoder();async function sign(token,timestamp,nonce,payload){const key=await crypto.subtle.importKey('raw',enc.encode(token),{name:'HMAC',hash:'SHA-256'},false,['sign']);const data=enc.encode(timestamp+'\n'+nonce+'\n'+payload);const out=new Uint8Array(await crypto.subtle.sign('HMAC',key,data));return [...out].map(x=>x.toString(16).padStart(2,'0')).join('')}
function config(){return{route:$('route').value.trim(),account:$('account').value.trim(),user:$('user').value.trim(),chat:$('chat').value.trim(),token:$('token').value}}
function valid(c){return c.route&&c.account&&c.user&&c.chat&&c.token.length>=16}
function add(kind,text,meta,id){if(id&&seen.has(id))return;if(id)seen.add(id);document.querySelector('.empty')?.remove();const el=document.createElement('div');el.className='bubble '+kind;el.textContent=text;const small=document.createElement('span');small.className='meta';small.textContent=meta;el.appendChild(small);$('timeline').appendChild(el);$('timeline').scrollTop=$('timeline').scrollHeight}
async function signedHeaders(c,payload){const timestamp=Math.floor(Date.now()/1000).toString(),nonce=crypto.randomUUID();return{'X-WebUI-Timestamp':timestamp,'X-WebUI-Nonce':nonce,'X-WebUI-Signature':await sign(c.token,timestamp,nonce,payload)}}
async function poll(){if(!connected)return;const c=config();const q=new URLSearchParams({route_key:c.route,external_user_id:c.user,external_chat_id:c.chat});const uri='/webui/api/replies?'+q;try{const headers=await signedHeaders(c,'GET\n'+uri);const response=await fetch(uri,{headers,cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const body=await response.json();for(const item of body.messages)add('bot',item.text,item.request_id,item.provider_message_id);$('status').textContent='已连接';$('status').classList.add('ok')}catch(error){$('status').textContent='读取失败 '+error.message;$('status').classList.remove('ok')}}
$('connect').addEventListener('click',()=>{const c=config();if(!valid(c)){alert('请填写完整配置，Token 至少 16 字符');return}connected=true;seen.clear();$('status').textContent='连接中';clearInterval(timer);poll();timer=setInterval(poll,1000)});
$('composer').addEventListener('submit',async event=>{event.preventDefault();const c=config(),text=$('text').value.trim();if(!connected||!valid(c)||!text)return;const id=crypto.randomUUID(),occurred=new Date().toISOString();const body=JSON.stringify({schema_version:1,external_account_id:c.account,external_message_id:id,external_user_id:c.user,external_chat_id:c.chat,conversation_type:'p2p',message_type:'text',text,occurred_at:occurred});try{const headers=await signedHeaders(c,body);headers['Content-Type']='application/json';const response=await fetch('/webui/api/messages?route_key='+encodeURIComponent(c.route),{method:'POST',headers,body});if(!response.ok)throw new Error('HTTP '+response.status);add('me',text,id,id);$('text').value='';setTimeout(poll,250)}catch(error){$('status').textContent='发送失败 '+error.message;$('status').classList.remove('ok')}});`
